POST http://localhost:8080/events
Content-Type: application/json

{
  "Name": "Meu evento",
  "Description": "Um evento muito maneiro",
  "Location": "Minha casa",
  "dateTime": "2025-01-01T15:30:00.000Z"
}
